#!/bin/sh
# Strip Cursor co-author trailers (runs after the message is finalized).
MSG_FILE="$1"
[ -f "$MSG_FILE" ] || exit 0

sed -i '/^[Cc]o-[Aa]uthored-[Bb]y:.*cursoragent@cursor\.com/d' "$MSG_FILE"
sed -i '/^[Cc]o-[Aa]uthored-[Bb]y:.*[Cc]ursor.*cursor\.com/d' "$MSG_FILE"
